version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.11.0-ce
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: docker build -t monacoind .

      - run:
          name: Push image to Docker Hub
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker tag monacoind "osyoyu/monacoind-docker:0.14.2"
            docker push "osyoyu/monacoind-docker:0.14.2"
